version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: trane-hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend-trane-hub
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/trane-hub
      JWT_SECRET: 823e0bc23b804e949a8911ae7478d07baed4b0700e5640b3a0a9f53db4410693
      SHOP_ID: 1025111
      PAYMENT_TOKEN: test_tWsFj0dKLwm9lpWbr7q2XrKg4fYSGVUTFqdHg1lDEA0
      FRONTEND_URL: http://localhost
      PORT: 4200
    volumes:
      - ./backend-trane-hub/uploads:/app/uploads
    ports:
      - "4200:4200"
    command: ["npm", "run", "start:prod"]

  frontend:
    build:
      context: ./frontend-trane-hub
      args:
        SERVER_URL: http://backend
        APP_URL: http://localhost
    depends_on:
      - backend
    environment:
      SERVER_URL: http://backend
      APP_URL: http://localhost
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

volumes:
  pgdata:
